### PR TITLE
Archiving 4chan threads now gives a timestamp, which makes determining whether or not the thread has died a lot easier.

### PR DESCRIPTION
**Pull request by WORD559**

### CODE REVIEW

**Comment by antonizoon** [comment]
Thanks, I wasn't able to figure out how to do this right, so this helps a lot.

**Comment by WORD559** [comment]
I made sure to update the setup.py and everything with new version numbers, so you should be able to update the pypi package, too

**Comment by antonizoon** [comment]
I'm sorry about the delay, I'm on a boat and can't deal with this until June 15at earliest.

**Comment by antonizoon** [comment]
The new package is now pushed.

**Pull request merged**
